Add template version to AndroidManifest.xml and Info.plist
flutter/games pull request #17
Opened 2023-12-20 08:49 UTC by filiph

For tracking purposes, we're adding a key-value pair to each game template. This can be used by the AdMob plugin to recognize that this is a Flutter game built on top of the template.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/games/blob/main/CONTRIBUTING.md

2023-12-20 09:07 UTC, domesticmouse approved these changes
Is template version all you want to track? Also, you may want to add a comment justifying to the template user why they should leave it in their published game.

2024-01-03 04:39 UTC, domesticmouse requested changes

2024-01-03 04:39 UTC, domesticmouse commented on templates/basic/android/app/src/main/AndroidManifest.xml
> +            <!-- Specifies the version of the game template for tracking purposes. -->
Change to "Specifies the version of the game template to understand template usage."

2024-01-03 04:39 UTC, domesticmouse commented on templates/card/android/app/src/main/AndroidManifest.xml
> +            <!-- Specifies the version of the game template for tracking purposes. -->
Change to "Specifies the version of the game template to understand template usage."

2024-01-03 04:39 UTC, domesticmouse commented on templates/endless_runner/android/app/src/main/AndroidManifest.xml
> +            <!-- Specifies the version of the game template for tracking purposes. -->
Change to "Specifies the version of the game template to understand template usage."

2024-01-03 12:10 UTC, filiph commented
I've changed the wording.

2024-01-03 20:19 UTC, domesticmouse approved these changes

2024-01-03 20:20 UTC, merged