[WIP] Initial code and infrastructure
flutter/games pull request #2
Opened 2023-11-06 14:04 UTC by filiph

Adding infrastructure from `flutter/samples`, and the first two templates.

As of creating this pull request, no template or sample is included. I wanted only to include infrastructure first so it's easier to talk about it. The intended file structure looks something like this:

```text
.
├── .github
├── .tools
├── templates
│   ├── game
│   ├── card_game
│   └── 2d_game
└── samples
	├── ads
	├── multiplayer
	└── ...
```

cc @domesticmouse for input

2023-11-06 14:05 UTC, filiph commented on .gitattributes
Do we absolutely need this? It's in `flutter/samples` and it looks like a good idea. But I'd love to keep the top-level as simple as possible.

2023-11-06 14:07 UTC, filiph commented on .github/dependabot.yaml
> +  - package-ecosystem: "npm"
I'm going to remove these shortly. Just wanted to have them as a template of sorts.

2023-11-06 14:08 UTC, filiph commented on .github/workflows/beta.yml
> +      - run: ./tool/flutter_ci_script_stable.sh
I intend to fix this and other paths once we agree on the file structure.

2023-11-06 14:09 UTC, filiph commented on .github/workflows/main.yml
> +        flutter_version: [stable, beta, master]
Do we really want to run the tests against the `master` channel, too? Is this worth it?

2023-11-06 14:09 UTC, filiph commented on .github/workflows/scorecards-analysis.yml
FWIW, I have no idea what these scorecards actually do or what they are.

2023-11-06 14:10 UTC, filiph commented on .tool/flutter_ci_script_beta.sh
> +    "add_to_app/android_view/flutter_module_using_plugin"
I will obviously replace these with the paths in this repo.

2023-11-06 14:11 UTC, filiph commented on .tool/flutter_ci_script_stable.sh
> +    "add_to_app/android_view/flutter_module_using_plugin"
And here.

2023-11-06 14:12 UTC, filiph commented on AUTHORS
Happy to remove if not needed, to keep the top-level clean.

2023-11-06 14:12 UTC, filiph commented on CONTRIBUTING.md
I have kept most of the text from `flutter/samples`, but adapted it to this repo.

2023-11-06 14:13 UTC, filiph commented on LICENSE
I'm pretty sure we'll need all these licenses (incl. fonts SIL) pretty soon, so I'm keeping the file as is from `flutter/samples`.

2023-11-06 14:13 UTC, filiph commented on PATENTS
Happy to lose this if it's not needed.

2023-11-07 00:58 UTC, domesticmouse approved these changes
I'd prefer the maintenance scripts at top level so they are easy and obvious to both maintain (for me) and delete (for people who fork this code and use it for their own needs)

2023-11-07 00:58 UTC, domesticmouse commented on .gitattributes
It makes GitHub sane on Windows. Without it things tend to go sideways real quick. I'd strongly advocate for keeping it so Windows hosted developers can submit PRs that don't make my eyes bleed.

2023-11-07 00:58 UTC, domesticmouse commented on .github/dependabot.yaml
> +  - package-ecosystem: "npm"
I prefer daily over weekly, but then I don't really care about `npm`. I'd strongly hope that we don't have much (if any) `npm` code in our samples.

2023-11-07 00:58 UTC, domesticmouse commented on .github/dependabot.yaml
> +      - "autosubmit"
We will need to hassle @godofredoc to make sure this repo has the tooling required to enable auto-landing of dependabot PRs once CI is green.

2023-11-07 00:58 UTC, domesticmouse commented on .github/workflows/beta.yml
> +      - run: ./tool/flutter_ci_script_stable.sh
I'd prefer these maintenance scripts at top level, not hidden in `tool`.

2023-11-07 00:58 UTC, domesticmouse commented on .github/workflows/main.yml
> +        flutter_version: [stable, beta, master]
The `flutter/samples` repo has `master` CI because it has code that was only compilable on `master`. That code has since aged out to only requiring `beta` so I could lose the master CI on `flutter/samples` but I find it a useful canary build over there.

I have no feelings one way or the other about `master` CI for `flutter/games`. I'm guessing `stable` and `beta` should be sufficient for now.

2023-11-07 00:58 UTC, domesticmouse commented on .github/workflows/scorecards-analysis.yml
Paging @godofredoc to explain what dark magic is contained in these `scorecards` runes

2023-11-07 00:58 UTC, domesticmouse commented on AUTHORS
I believe this is required by OSPO. Prefer to keep.

2023-11-07 00:58 UTC, domesticmouse commented on PATENTS
I don't have it for `flutter/codelabs`

2023-11-07 14:32 UTC, filiph commented on .github/workflows/beta.yml
> +      - run: ./tool/flutter_ci_script_stable.sh
Will do.

2023-11-07 14:35 UTC, filiph commented on .github/workflows/main.yml
> +        flutter_version: [stable, beta, master]
Ok, will remove `master`, at least for now.

2023-11-07 14:36 UTC, filiph commented on PATENTS
Ok, removing.

2023-11-07 14:41 UTC, filiph commented on .github/dependabot.yaml
> +  - package-ecosystem: "npm"
Yep, `npm` is now gone, and the interval will be `daily` for others.

2023-11-07 22:57 UTC, domesticmouse requested changes
Prune the list of projects to ones that exist in this repo, then land this PR. Thanks!

2023-11-07 22:57 UTC, domesticmouse commented on flutter_ci_script_beta.sh
> +    "add_to_app/android_view/flutter_module_using_plugin"
Before this lands, you'll need to strip the project names back to what is present. Otherwise all follow up PRs will be blocked until this list is pruned. =)

(It's fun that PRs that change CI don't actually test the CI as it is becoming, but as it was. So debugging CI is a fast loop of burning failures. Fun times)

2023-11-07 22:57 UTC, domesticmouse commented on flutter_ci_script_stable.sh
> +    "add_to_app/android_view/flutter_module_using_plugin"
ditto

2023-11-08 09:31 UTC, filiph commented on flutter_ci_script_beta.sh
> +    "add_to_app/android_view/flutter_module_using_plugin"
Done

2023-11-08 09:33 UTC, filiph commented
Ok, I think this is ready for one final round.

I added the (pre-LGTM'd) code from `filiph/game_template` into `templates/basic` and `templates/card`. I also _think_ the CI now corresponds to what's in the repo.

2023-11-08 09:35 UTC, domesticmouse commented
> Ok, I think this is ready for one final round.
> 
> 
> 
> I added the (pre-LGTM'd) code from `filiph/game_template` into `templates/basic` and `templates/card`. I also _think_ the CI now corresponds to what's in the repo.

The easy way to find out is to land this PR and then bring #3 up to date and see if it CIs straight. It'll mean updating #3 to include that new project in CI 😎

2023-11-08 09:36 UTC, filiph commented
Shall I hit the button on this one, then? I'm happy to add the change to #3. (And sorry, I only saw your comment on #3 now.)

2023-11-08 09:37 UTC, filiph commented
Ahhhh, no! I see a problem. One sec.

2023-11-08 09:37 UTC, domesticmouse commented
@filiph do you want to have the honours, or do you want me to land this PR?

2023-11-08 09:39 UTC, filiph commented
Ok, _now_ I'm happy. I see that you're okay with this, so I'll do the honors.

2023-11-08 09:39 UTC, merged

2023-11-08 10:28 UTC, filiph commented
Gah, I forgot to cc @johnmccutchan on this PR. John, if you want to review the code again, please feel free. The code is 99.9% the same as the one you reviewed over at https://github.com/filiph/game_template.